### PR TITLE
Solved glitches in auto-expand panes and replaced original base64 imgs

### PR DESCRIPTION
**Pull request by ldetomi**
Solved various glitches in new auto-expand panes and replaced original base64 encoded images with original .png ones in LESS code. Base64 encoding is made at process time generating final CSS code

### CODE REVIEW

**Comment by akaJes** [comment]
Hi @ldetomi 
Thank you for your help with this project

I don't think that is necessary to remove base64 - it was made with a goal to minimize dependencies
And about pin icons - i have started to create these with GIMP from original png
[Pin-96.zip](https://github.com/akaJes/golden-layout/files/1080502/Pin-96.zip)
and online tool for converting to base64 http://freeonlinetools24.com/base64-image

**Comment by ldetomi** [comment]
I still continue using Base64, simply in LESS code there is reference to original images and then while converting LESS to CSS, it convert them again into base64. Please compare original LESS code and final CSS processed ones

This is very useful for users that eventually wants to replace icons. They can simply replace img files or change path into LESS code and then processing re-create base64. Final result is the same but development is easier

In the future I would like to work on updating icons to make them more coherent and different for each theme, maybe using icon-fonts to let users change colors according to themes simply using CSS `color` property

**Comment by akaJes** [comment]
Yes I agree, dynamic generation is better than manual work :)
And about the pin - my old version is so ugly and blur?
Is it possible to do it better and with the same size as other icons?
can you help with these?

**Comment by ldetomi** [comment]
Sure that I can help you with icon. For the moment I use only one rotated via CSS when docked. If you agree, we could think to replace all icons with new ones (as said, I thought to use svg ones or icon-fonts) with a specific commit after merge of your branch into official one. Technically, icon set replace is not dependent by your new features (by side, very nice features :-) )

I have also in mind to revamp all color themes, make them coherent between them and more optimized. Probably, I'll start from scratch replicating as more as possible actual L&F but with a better organization and a specific attention also to touch devices. 

Anyway, I'd do this only after your fork will be merged into master repository. Do you think could be happen soon?

**Comment by akaJes** [comment]
yes, it could be better solution with css rotation (i missed it - because
you have attached old icons)
I think after removing old files and unuseful comments we can apply ours PRs

16 черв. 2017 15:13 "Luca" <notifications@github.com> пише:

**Comment by ldetomi** [comment]
I left commented old lines to highlight my edits but if you prefer, you can delete them.

Have you read other comments in main original thread? there were some issues (and known bugs) noted into it. Maybe, if not too difficult, you could consider to fix them. I hope that you could :-)

**Comment by akaJes** [comment]
better is just to remove unused code - the github  shows all changes
perfectly :)
When you remove it, i'll commit PR

16 черв. 2017 16:37 "Luca" <notifications@github.com> пише:

**Comment by ldetomi** [comment]
Done it! :-)

**Comment by akaJes** [comment]
How about files?
src/img/lm_docked_white.png and black

**Comment by ldetomi** [comment]
I left them because in LESS code it remained commented reference to them. If a user prefer to use a dedicated icon (I added a comment to specify this in code) instead of "rotate" original one, can do it simply switching lines.

I think that we can mantain this "temp" feature for a while, maybe taking a decision after discussing it with other users after merging.

When I'll work on themes revamp, I'll finally replace all icons and solved this topic

**Pull request merged**
